add liquality
rsksmart/2wp-app pull request #214
Opened 2022-04-18 21:50 UTC by hard75

2022-04-19 17:12 UTC, ronaldsg20 requested changes
Please remove the `.env` file too

2022-04-19 17:12 UTC, ronaldsg20 commented on src/components/exchange/SelectBitcoinWallet.vue
> +        break;
Please use the value stored in `constants` instead of the plain string

2022-04-20 17:22 UTC, josedahlquist requested changes
Please remove all the unrelated files, you may want to include them in the .gitignore file so it doesn't happen again

2022-04-22 03:39 UTC, jeremy-then commented
> Please remove the `.env` file too

Yes, but I think it's better to revert all the commits, implement the required changes, like adding the .env to the .gitignore file, commit them and push the changes with force (-f). Because right now the .env file is in the commit history and we better remove it.

2022-04-27 16:33 UTC, ronaldsg20 commented on src/components/exchange/ConnectDevice.vue
> +        <v-img v-class="{  }" :src="deviceImagePath" height="300" contain />
I think It shouldn't have an empty `v-class` attribute

2022-04-27 19:18 UTC, ronaldsg20 approved these changes

2022-04-27 23:16 UTC, jeremy-then approved these changes
LGTM.

2022-05-02 03:00 UTC, merged