change tooltip account
rsksmart/2wp-app pull request #231
Opened 2022-06-08 14:14 UTC by hard75

2022-06-08 20:49 UTC, josedahlquist submitted a review, later dismissed

2022-06-08 22:33 UTC, jeremy-then approved these changes
LGTM.

2022-08-10 13:52 UTC, leoiovlabs requested changes

2022-08-10 13:52 UTC, leoiovlabs commented on src/components/create/PegInAccountSelect.vue
>                  Native segwit is coming soon for Ledger devices!
This text should be removed.

2022-08-24 07:37 UTC, ronaldsg20 approved these changes

2022-08-25 12:21 UTC, leoiovlabs approved these changes
LGTM

2022-08-26 14:29 UTC, merged