Liquality autodetection
rsksmart/2wp-app pull request #269
Opened 2022-08-08 17:03 UTC by ronaldsg20

2022-08-08 17:53 UTC, josedahlquist requested changes

2022-08-08 17:53 UTC, josedahlquist commented on src/components/create/SendBitcoin.vue
> +    console.log(this.showDialog);
this should not be here

2022-08-08 17:53 UTC, josedahlquist commented on src/components/exchange/ConnectDevice.vue
> +                 :disabled="sendBitcoinState === 'error' || walletName ==='Liquality'"
I think the button should be hidden rather than disabled if the wallet is not an HW wallet

2022-08-08 17:53 UTC, josedahlquist commented on src/services/LiqualityService.ts
> +        reject(new Error('Liquality software wallet not installed on your browser </br> <a target=\'_blank\' href=\'https://developers.rsk.co/solutions/liquality/\'/>Click here to know how to enable
I don't think we should be creating markup in a JS error.
instead I suggest creating a specific type of `Error` class that is later handled in the vue component to display the proper information
```suggestion
        reject(new LiqualityDetectionError('Liquality software wallet not installed on your browser'));
```

2022-08-08 17:53 UTC, josedahlquist commented on src/services/WalletService.ts
> +        message = 'Error balance';
```suggestion
        message = 'Error fetching balance';
```

2022-08-24 07:14 UTC, ronaldsg20 reviewed
LGTM

2022-08-24 15:40 UTC, alexjavabraz approved these changes
LGTM

2022-08-24 19:31 UTC, josedahlquist approved these changes

2022-08-24 19:31 UTC, josedahlquist commented on src/components/exchange/DeviceErrorDialog.vue
> +          <p class="justify-center">
```suggestion
          <p class="justify-center" v-if="urlToMoreInformation">
```

2022-08-24 20:35 UTC, merged