Confirm liquality style
rsksmart/2wp-app pull request #276
Opened 2022-08-22 13:49 UTC by hard75

2022-08-22 15:31 UTC, josedahlquist reviewed
except for the console log, this lgtm

2022-08-22 15:31 UTC, josedahlquist commented on src/components/liquality/ConfirmLiqualityTransaction.vue
> +    console.log('>>>>>>>>>>', this.pegInTxState.normalizedTx);
Please remove this console log

2022-08-22 19:23 UTC, josedahlquist approved these changes

2022-08-23 14:09 UTC, leoiovlabs approved these changes
LGTM

2022-08-25 12:31 UTC, leoiovlabs requested changes
Remove changes in package-lock.json

2022-08-26 06:15 UTC, ronaldsg20 approved these changes
LGTM

2022-08-29 17:32 UTC, josedahlquist approved these changes

2022-08-29 17:33 UTC, merged