pegin view success update
rsksmart/2wp-app pull request #304
Opened 2022-09-14 20:41 UTC by hard75

2022-09-15 19:23 UTC, alexjavabraz approved these changes
LGTM

2022-09-19 15:03 UTC, ronaldsg20 submitted a review, later dismissed
LGTM

2022-09-20 19:59 UTC, josedahlquist approved these changes

2022-09-21 14:55 UTC, alexjavabraz approved these changes
LGTM

2022-10-05 15:04 UTC, alexjavabraz commented on src/components/exchange/TxSummary.vue
> +    let result;
You can use:
let result = this.VALUE_INCOMPLETE_MESSAGE;
Without else.

2022-10-05 15:09 UTC, alexjavabraz requested changes

2022-10-05 15:09 UTC, alexjavabraz commented on src/components/exchange/TxSummary.vue
> +    }
```suggestion
    let result = this.VALUE_INCOMPLETE_MESSAGE;
    if (this.refundAddress !== '0x') {
      result = this.refundAddress;
    }
```

2022-10-05 20:29 UTC, hard75 commented on src/components/exchange/TxSummary.vue
> +    }
ok, it's fine

2022-10-06 12:30 UTC, alexjavabraz submitted a review, later dismissed
LGTM

2022-10-06 16:41 UTC, alexjavabraz submitted a review, later dismissed
LGTM

2022-10-06 16:43 UTC, ronaldsg20 approved these changes

2022-10-06 16:43 UTC, ronaldsg20 approved these changes

2022-10-06 20:23 UTC, alexjavabraz approved these changes

2022-10-07 15:42 UTC, leoiovlabs approved these changes
LGTM

2022-10-07 17:05 UTC, merged