Changing message when the wallet is Liquality
rsksmart/2wp-app pull request #326
Opened 2022-09-29 20:56 UTC by alexjavabraz

2022-09-30 15:18 UTC, ronaldsg20 approved these changes

2022-10-03 16:01 UTC, josedahlquist requested changes
The story requested a different message

2022-10-03 16:01 UTC, josedahlquist commented on src/components/exchange/ConnectDevice.vue
> +        <h1>Enable your {{ walletName }}</h1>
```suggestion
        <h1>Enable {{ walletName }} wallet</h1>
```

2022-10-03 17:15 UTC, ronaldsg20 approved these changes

2022-10-04 17:41 UTC, leoiovlabs approved these changes
LGTM

2022-10-04 17:45 UTC, josedahlquist approved these changes

2022-10-04 17:55 UTC, merged