update deployed URLs on workflows
rsksmart/2wp-app pull request #369
Opened 2022-12-14 20:36 UTC by ronaldsg20

**Updated**
- Testnet prod
- Mainet prod

2022-12-14 21:16 UTC, alexjavabraz approved these changes
LGTM

2022-12-15 13:49 UTC, juan-rsk requested changes
Please, change `aws-region: us-east-2` for `aws-region: us-east-1`

2022-12-16 15:59 UTC, juan-rsk approved these changes
LGTM

2022-12-19 14:15 UTC, josedahlquist approved these changes

2022-12-19 14:15 UTC, merged