Customize vue-tour for pegout
rsksmart/2wp-app pull request #484
Opened 2023-05-24 21:12 UTC by julia-zack

2023-05-25 01:29 UTC, ronaldsg20 requested changes

2023-05-25 01:29 UTC, ronaldsg20 commented on src/components/pegout/PegOutForm.vue
> +    this.$tours.pegOutTour.start();
we should check the cookie value in the `mounted` hook to start the tour, otherwise it only be started with the user click

2023-05-29 13:45 UTC, lserra-iov approved these changes

2023-05-29 14:40 UTC, ronaldsg20 approved these changes

2023-05-31 15:38 UTC, leoiovlabs approved these changes
LGTM

2023-05-31 16:01 UTC, merged