Send sessionId registering a tx
rsksmart/2wp-app pull request #611
Opened 2023-11-17 14:54 UTC by lserra-iov

Add session id required to register a transaction using the register endpoint (https://github.com/rsksmart/2wp-api/pull/263).
Send an empty string for pegouts until we modify sessions handling.

2023-11-20 16:49 UTC, alexjavabraz requested changes
Please add a simple validation to call the /register endpoint

2023-11-20 16:49 UTC, alexjavabraz commented on src/common/services/ApiService.ts
>        axios.post(`${ApiService.baseURL}/register`, {
avoid to call /register endpoint it some of the parameters are null for example:

if (sessionId === null || txHash === null || type === null )
 return;

2023-11-23 15:30 UTC, ronaldsg20 approved these changes
LGTM

2023-11-23 19:38 UTC, alexjavabraz approved these changes
LGTM

2023-11-23 19:43 UTC, merged