refactor: text on pegout and pegin options, title on home
rsksmart/2wp-app pull request #739
Opened 2024-06-17 18:25 UTC by annipi

[TWPAPP-751](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-751)

<img width="250" alt="Screenshot 2024-06-17 at 1 21 59 PM" src="https://github.com/rsksmart/2wp-app/assets/7018960/c11dab94-bdcf-4fdd-a72e-0ba2690f3b2e">
<img width="961" alt="Screenshot 2024-06-17 at 1 22 09 PM" src="https://github.com/rsksmart/2wp-app/assets/7018960/694ce87b-65da-4159-b365-87384308ed0a">
<img width="1399" alt="Screenshot 2024-06-17 at 1 22 30 PM" src="https://github.com/rsksmart/2wp-app/assets/7018960/a7f6c3a5-b9ac-4b30-a7e0-099d6a4d8c24">

2024-06-17 20:39 UTC, alexjavabraz approved these changes
LGTM

2024-06-17 20:45 UTC, ronaldsg20 requested changes

2024-06-17 20:45 UTC, ronaldsg20 commented on src/common/utils/utils.ts
> +}
Please add this functionality to `EnvironmentContextProviderService`, this can be removed

2024-06-18 19:36 UTC, lserra-iov approved these changes

2024-06-18 22:08 UTC, ronaldsg20 approved these changes

2024-06-22 03:00 UTC, leoiovlabs approved these changes
LGTM

2024-06-25 17:33 UTC, merged