refactor: home buttons
rsksmart/2wp-app pull request #756
Opened 2024-07-04 20:55 UTC by annipi

[TWPAPP-758](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-758)

<img width="450" alt="Screenshot 2024-07-04 at 3 47 37 PM" src="https://github.com/rsksmart/2wp-app/assets/7018960/443ffa9e-ed7f-4c94-9d4d-0fbfd46f48fd">

<img width="436" alt="Screenshot 2024-07-04 at 3 48 26 PM" src="https://github.com/rsksmart/2wp-app/assets/7018960/56b8704e-5cb7-4152-bcdf-7bf8d348aa4b">

2024-07-05 13:07 UTC, alexjavabraz requested changes

2024-07-05 13:07 UTC, alexjavabraz commented on src/common/views/Home.vue
> +.border-box {
Please, send this style to css file.

2024-07-05 15:46 UTC, alexjavabraz approved these changes
LGTM

2024-07-08 17:26 UTC, leoiovlabs approved these changes
LGTM

2024-07-08 18:40 UTC, merged