Show pegin wallets based on feature flags
rsksmart/2wp-app pull request #848
Opened 2024-10-10 18:23 UTC by lserra-iov

2024-10-14 19:22 UTC, ronaldsg20 approved these changes

2024-10-14 21:35 UTC, alexjavabraz requested changes
Just to clarify the source of that field, in order to make sure the env_variable name will be the correct one.

2024-10-14 21:35 UTC, alexjavabraz commented on src/common/components/exchange/SelectBitcoinWallet.vue
> +      const walletName = wallet.constant as BtcWallet;
```suggestion
      const walletConfJsonConstant = wallet.constant as BtcWallet;
```

2024-10-14 21:35 UTC, alexjavabraz commented on src/common/components/exchange/SelectBitcoinWallet.vue
> +      const flag = getFeature.value(FeatureNames[walletName]);
```suggestion
      const flag = getFeature.value(FeatureNames[walletConfJsonConstant]);
```

2024-10-16 14:29 UTC, alexjavabraz approved these changes
LGTM

2024-10-16 21:10 UTC, annipi approved these changes
LGTM!

2024-10-18 15:48 UTC, leoiovlabs approved these changes
LGTM

2024-10-21 05:34 UTC, merged