Fix: Blockbook not responding
rsksmart/2wp-app pull request #957
Opened 2024-12-05 21:11 UTC by annipi

[TWPAPP-1020](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1020)

This PR requires to merge [PR955](https://github.com/rsksmart/2wp-app/pull/955) (This PR955 requires `@rsksmart/flyover-sdk@1.6.2`, `@rsksmart/bridges-core-sdk@0.4.1` )

<img width="1065" alt="Screenshot 2024-12-05 at 8 45 51 AM" src="https://github.com/user-attachments/assets/5d1775e1-6280-413c-a487-34539a696bc4">

2024-12-06 14:55 UTC, lserra-iov requested changes

2024-12-06 14:55 UTC, lserra-iov commented on package.json
These dependencies seem to have been added by mistake, please remove them.

2024-12-06 15:28 UTC, annipi commented on package.json
Good catch thanks

2024-12-09 12:09 UTC, alexjavabraz approved these changes
LGTM

2024-12-10 15:02 UTC, merged